# Generated by Django 6.0.6 on 2026-06-30 14:59

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_encrypt_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ai_summary',
            field=core.encryption.EncryptedJSONField(blank=True, help_text='Structured analysis results from Claude (encrypted)', null=True, verbose_name='AI analysis summary'),
        ),
    ]
