# Generated by Django 6.0.6 on 2026-06-09 22:37

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_encrypt_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ai_summary',
            field=core.encryption.EncryptedJSONField(blank=True, help_text='Structured analysis results from OpenAI (encrypted)', null=True, verbose_name='AI analysis summary'),
        ),
        migrations.AlterField(
            model_name='document',
            name='condition_tags',
            field=core.encryption.EncryptedJSONField(blank=True, default=list, help_text='List of condition names this document relates to (encrypted at rest)', verbose_name='Condition tags'),
        ),
    ]
