# Generated by Django 6.0.6 on 2026-06-09 22:37

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_encrypt_existing_pii_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=core.encryption.EncryptedCharField(blank=True, max_length=255, verbose_name='Phone number'),
        ),
    ]
