# Generated by Django 6.0.6 on 2026-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_organization_restrict_caseworker_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deletion requested at"
            ),
        ),
    ]
