# Generated by Django 6.0.6 on 2026-08-02 17:37

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_deletion_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationinvitation",
            name="case_payload",
            field=core.encryption.EncryptedJSONField(
                blank=True,
                help_text="Case details to create when the invitation is accepted",
                null=True,
                verbose_name="Pending case payload",
            ),
        ),
    ]
